apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openam
spec:
  replicas: {{default 1 .Values.replicaCount | quote}}
  template:
    metadata:
      labels:
        app: openam
      # This is really only needed if we use Petset alpha
#      annotations:
#        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: openam
        image: {{ default "forgerock/openam" .Values.image}}:{{ default "latest" .Values.imageTag}}
        imagePullPolicy: {{default "IfNotPresent" .Values.pullPolicy}}
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: openam-secrets
          mountPath: /root/openam
          #readOnly: true
        env:
        {{- range $key, $value := .Values.openam_env_vars }}
          - name: {{ $key }}
            value: {{ $value  | quote }}
        {{ end }}
      volumes:
      - name: openam-secrets
        secret:
          secretName: openam-secrets