# Secrets for OpenAM stack deployment. This will be mounted on all containers so they can get their
# passwords, etc.
# Note that secret vals are base 64 encoded
# base64 of 'password' is 'cGFzc3dvcmQ='
# Watch for trailing \n when you encode!
apiVersion: v1
kind: Secret
metadata:
    name: "{{.Release.Name}}-secrets"
    annotations:
      "helm.sh/hook": pre-install

type: Opaque
data:
  dirmanager.pw:    {{ b64enc "password" }}
  am.enc.key: TzZRV3dIUE80b3MrekV6M05xbi8yZGFBWVd5aUZFMzINCg==
  amadmin.pw:   {{ b64enc "password" }}
