apiVersion: v1
kind: Service
metadata:
  name: openam
spec:
  type: NodePort
  ports:
    - port: 80
      name: am80
      targetPort: 8080
      nodePort: 30080
    - port: 443
      targetPort: 8443
      nodePort: 30443
      name: am443
  selector:
    app: openam
{{if .Values.externalConfigStore}}
---
apiVersion: v1
kind: Service
metadata:
  name: opendj
spec:
  type: ClusterIP
  ports:
    - port: 389
      name: ldap
      targetPort: 389
    - port: 4444
      name: djadmin
      targetPort: 4444
      #
  # Note the DJ container is in the same pod as openam - so we use the openam selector
  selector:
    app: opendj
{{end}}