# We use a single OpenDJ instance as the config and CTS store for the cluster
# This instance is ephemeral - just for demo purposes
apiVersion: v1
kind: ReplicationController
metadata:
  name: apache-rc
spec:
  replicas: 1
  selector:
    name: apache
  template:
    metadata:
      labels:
        name: apache
        agent: apache
    spec:
      containers:
      - name: apache
        image: wstrange/apache-agent-nightly
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
          - name: secrets
            mountPath: /secrets
            readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: fr-secrets