apiVersion: v1
kind: Service
metadata:
  name: openam-svc
spec:
  type: NodePort
  #type: ClusterIP
  #type: LoadBalancer
  ports:
    - port: 80
      targetPort: openam
      nodePort: 30080
  selector:
    site: site1