apiVersion: v1
kind: Service
metadata:
  name: openam
spec:
  #type: NodePort
  #type: ClusterIP
  #type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  #    nodePort: 30080
  selector:
    site: site1
