apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: openam-a
  name: openam-a
spec:
  replicas: 1
  selector:
    name: openam-a
  template:
    metadata:
      labels:
         name: openam-a
         site: site1
    spec:
      containers:
      - name: openam-a
        image: forgerock/openam
        #imagePullPolicy: Always
        ports:
          - name: openam
            containerPort: 8080
        volumeMounts:
          - name: openam-disk-a
            mountPath: /root/openam
          - name: secrets
            mountPath: /secrets
      - name: ssoadm
        image: wstrange/ssoadm-nightly
        volumeMounts:
          - name: openam-disk-a
            mountPath: /root/openam
          - name: secrets
            mountPath: /secrets
      volumes:
        - name: openam-disk-a
          persistentVolumeClaim:
            claimName: openam-pvc-a
        - name: secrets
          secret:
            secretName: fr-secrets
