kind: PersistentVolume
apiVersion: v1
metadata:
  name: data01
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data01"
  persistentVolumeReclaimPolicy: Recycle

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data02
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data02"
  persistentVolumeReclaimPolicy: Recycle
