apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: ssoconfig
spec:
  selector:
    matchLabels:
      app: ssoconfig
  template:
    metadata:
      name: ssoconfig
      labels:
        app: ssoconfig
    spec:
      containers:
      - name: ssoconfig
        image: forgerock/ssoconfig:nightly
        imagePullPolicy: Always
        volumeMounts:
          - name: secrets
            mountPath: /secrets
        env:
        - name: LB_PRIMARY_URL
          valueFrom:
            configMapKeyRef:
              name: am-config
              key: openam.fqdn
        - name: COOKIE_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: am-config
              key: openam.cookiedomain
        - name: OPENAM_CONFIG_URL
          valueFrom:
            configMapKeyRef:
              name: am-config
              key: openam.configurl
      restartPolicy: Never
      volumes:
        - name: secrets
          secret:
            secretName: fr-secrets
