kind: PersistentVolume
apiVersion: v1
metadata:
  name: frstack
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/share
    server: 10.240.23.185