kind: PersistentVolume
apiVersion: v1
metadata:
  name: frstack
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data01"
  persistentVolumeReclaimPolicy: Recycle
