apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: openam-a
  name: openam-a
spec:
  replicas: 1
  selector:
    name: openam-a
  template:
    metadata:
      labels:
         name: openam-a
         site: site1
    spec:
      containers:
      - name: openam-a
        image: wstrange/openam-nightly
        env:
          - name: "OPENAM_INSTANCE"
            value: "openam01"
        ports:
        - name: openam
          containerPort: 8080
#        volumeMounts:
#        - name: openam-disk-a
#          mountPath: /root/openam
#      volumes:
#        - name: openam-disk-a
#          gcePersistentDisk:
#            pdName: openam-disk-a
#            fsType: ext4
##          nfs:
#            server: 10.240.23.185
#            path: /opt/share/openam-a
#          persistentVolumeClaim:
#            claimName: pv01claim
