# This creates a k8 service mapped to an external (outside of k8) OpenDJ service
apiVersion: v1
kind: Service
metadata:
  name: opendj
  labels:
    name: opendj
spec:
  ports:
    - port: 389
      targetPort: 389
      name: ldap
    - port: 4444
      targetPort: 4444
      name: dj-admin
