apiVersion: v1
kind: Service
metadata:
  name: opendj-cts
spec:
  type: NodePort
  ports:
    - port: 389
      targetPort: ldap
      protocol: "TCP"
      name: opendj-389
      nodePort: 30389
  selector:
    name: opendj-cts