apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openam
spec:
  replicas: {{default 1 .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: openam
#      annotations:
#        pod.beta.kubernetes.io/init-containers: '[
#        {
#            "name": "test",
#            "image": "alpine",
#            "command":  [ "/bin/sh", "-c", "echo hello > /tmp/openam/foo "],
#            "volumeMounts": [
#                        {
#                            "name": "openam-home",
#                            "mountPath": "/tmp/openam"
#                        }]
#        }
#        ]'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: openam
        image: {{ default "forgerock/openam" .Values.image}}:{{ default "latest" .Values.imageTag}}
        imagePullPolicy: {{default "IfNotPresent" .Values.pullPolicy}}
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: openam-secrets
          mountPath: /root/openam/openam
        env:
        {{- range $key, $value := .Values.openam_env_vars }}
          - name: {{ $key }}
            value: {{ $value  | quote -}}
        {{ end }}
      volumes:
      - name: openam-secrets
        secret:
          secretName: openam-secrets