# Default values for openam-dev.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

image: forgerock/openam
imageTag: latest

replicaCount: 1

#serverUrl: http://openam.test.com:8080

# Server URL *within* the k8s cluster
serverUrl: http://openam:80

# What OpenAM is known by *outside* the cluster
loadBalancerUrl: "http://openam.test.com:30080/openam"

fqdnHostname: openam.test.com
amadmin_pw: password

# Suffix for OpenDJ config store
rootSuffix:  "dc=openam,dc=forgerock,dc=org"


# Items below here control whether or not we use
# an external OpenDJ config store
externalConfigStore: true

djImage: forgerock/opendj
djImageTag: latest
