apiVersion: v1
kind: Service
metadata:
  name: opendj
  labels:
    app: opendj
spec:
  ports:
  - port: 389
    name: ldap
  - port: 636
    name: ldaps
  - port: 4444
    name: dj-admin
  - port: 8989
    name: dj-replication
  # *.opendj.default.svc.cluster.local
  clusterIP: None
  selector:
    app: opendj