apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: opendj
spec:
  serviceName: "opendj"
  replicas: 2
  template:
    metadata:
      labels:
        app: opendj
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      #terminationGracePeriodSeconds: 0
      containers:
      - name: opendj
        image: forgerock/opendj:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 389
          name: ldap
        - containerPort: 686
          name: ldaps
        - containerPort: 4444
          name: djadmin
#        env:
#        - name: BOOTSTRAP
#          value: /var/tmp/config/djconfig
        volumeMounts:
          - name: opendj-data
            mountPath: /opt/opendj/data
          - name: secrets
            mountPath: /var/secrets/opendj
            readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: fr-secrets
  volumeClaimTemplates:
  - metadata:
      name: opendj-data
#      annotations:
#        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
