# Host Path based PVs - for testing only!
# This will only work on a single node cluster!
# For a "real" cluster you need to create PVs that are available across nodes
# See the Kube docs on creating PVs
# For the petset example, the petset storage provisioner will grab one of these available volumes
# If you scale to more than 2 pets, add more storage volumes here.

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data01
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/kube/data01
  persistentVolumeReclaimPolicy: Recycle

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data02
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/kube/data02"
  persistentVolumeReclaimPolicy: Recycle
