apiVersion: v1
kind: Service
metadata:
  name: opendj
  label:
    - name: opendj
spec:
  ports:
    - port: 389
      targetPort: ldap
      protocol: "TCP"
      name: opendj-389
  selector:
    name: opendj
# Uncomment to access externally
#  createExternalLoadBalancer: true
