# The configurator needs to address each OpenAM node seperately to configure it
# Hence the need to expose a each instance as a service
apiVersion: v1
kind: Service
metadata:
  name: openam-svc-a
  label:
    name: openam-svc-a
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: "TCP"
      name: openam-a
  selector:
    name: openam-a
#  type: NodePort
#  publicIPs:
#    - 10.245.1.3
# If for some reason you need to admin the instance externally
# uncomment this
#  createExternalLoadBalancer: true
