apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: openam
  name: openam
spec:
  replicas: 1
  selector:
    name: openam
  template:
    metadata:
      labels:
         name: openam
         site: site1
    spec:
      containers:
      - name: openam
        image: wstrange/openam-nightly
        ports:
          - name: openam
            containerPort: 8080
        volumeMounts:
          - name: openam-root
            mountPath: /root/openam
          - name: secrets
            mountPath: /secrets
      # - name: logging-sidecar
      #   image: gcr.io/google_containers/fluentd-sidecar-gcp:1.3
      #   resources:
      #     limits:
      #       cpu: 100m
      #       memory: 200Mi
      #   env:
      #     - name: FILES_TO_COLLECT
      #       value: "/mnt/openam/debug/CoreSystem /mnt/openam/log/access.csv"
      #   volumeMounts:
      #     - name: openam-root
      #       readOnly: true
      #       mountPath: /mnt
      volumes:
        - name: secrets
          secret:
            secretName: fr-secrets
        - name: openam-root
          emptyDir: {}
