apiVersion: v1
kind: Service
metadata:
  name: openidm
  labels:
    name: openidm
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: openidm
      protocol: "TCP"
      name: openidm-80
  sessionAffinity: ClientIP
  selector:
    name: openidm
