apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: openidm
  name: openidm
spec:
  replicas: 1
  selector:
    name: openidm
  template:
    metadata:
      labels:
         name: openidm
    spec:
      containers:
      - name: openidm
        image: wstrange/openidm-nightly
        ports:
          - name: openidm
            containerPort: 8080
        volumeMounts:
          - name: secrets
            mountPath: /secrets
      # - name: logging-sidecar
      #   image: gcr.io/google_containers/fluentd-sidecar-gcp:1.3
      #   resources:
      #     limits:
      #       cpu: 100m
      #       memory: 200Mi
      #   env:
      #     - name: FILES_TO_COLLECT
      #       value: "/mnt/openidm/debug/CoreSystem /mnt/openidm/log/access.csv"
      #   volumeMounts:
      #     - name: openidm-root
      #       readOnly: true
      #       mountPath: /mnt
      volumes:
        - name: secrets
          secret:
            secretName: fr-secrets
