apiVersion: v1
kind: Service
metadata:
  name: openam
  labels:
    name: openam
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: openam
      protocol: "TCP"
      name: openam-80
  sessionAffinity: ClientIP
  selector:
    site: site1
