apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.djInstance }}
spec:
  #type: NodePort
  clusterIP: None
  ports:
    - port: 389
      name: ldap
      targetPort: 389
#      nodePort: {{ default 30389 .Values.ldapNodePort }}
    - port: 4444
      name: djadmin
      targetPort: 4444
#      nodePort: {{ default 30444 .Values.ldapAdminPort }}
  #
  # Note the DJ container is in the same pod as openam - so we use the openam selector
  selector:
    djInstance: {{ .Values.djInstance }}