# Elasticsearch for audit logs
# Todo: figure out how to load schema after ES starts
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    name: kibana-es
  type: NodePort
  ports:
  - port: 80
    targetPort: 5601
    nodePort: 30200


---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    name: kibana-es
  ports:
  - port: 9200
    name: es-9200
    targetPort: 9200
  - port: 9300
    name: es-9300
    targetPort: 9300

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-es
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kibana-es
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch
        ports:
          - containerPort: 9200
          - containerPort: 9300
        # todo: mount persistent volume on /usr/share/elasticsearch/data
      - name: kibana
        image: kibana
        ports:
          - containerPort: 5601
        env:
          - name: ELASTICSEARCH_URL
            #value: http://elasticsearch:9200/
            #value: http://elasticsearch.default.svc.cluster.local:9200
            value: http://$(ELASTICSEARCH_PORT_9200_TCP_ADDR):9200
