# Run OpenIDM on k8
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: openidm
  name: openidm
spec:
  containers:
  - name: openidm
    image: wstrange/openidm-nightly
    ports:
    - containerPort: 8080
