apiVersion: v1
kind: Service
metadata:
  name: opendj
spec:
  ports:
    - port: 389
      targetPort: ldap
      protocol: "TCP"
      name: opendj-389
  selector:
    name: opendj

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: opendj
  name: opendj
spec:
  replicas: 1
  template:
    metadata:
      labels:
         name: opendj
    spec:
      containers:
      - name: opendj
        image: forgerock/opendj:nightly
        ports:
        - name: ldap
          containerPort: 389
          protocol: TCP
# For now we will leave DJ disk as ephemeral. It will dissapear when the container does
#        volumeMounts:
#        - name: opendj-disk
#          mountPath: /opt/opendj/instances/instance1
#      volumes:
#        - name: opendj-disk
#          persistentVolumeClaim:
#            claimName: opendj-storage
