# Run OpenIDM on k8
# Service definition
apiVersion: v1
kind: Service
metadata:
  name: openidm
spec:
  selector:
    name: openidm
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30100

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openidm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: openidm
    spec:
      containers:
      - name: openidm
        image: forgerock/openidm:nightly
        # env:
        #   - name: OPENIDM_PROJECT_DIR
        #     value: /config/stack-config/openidm
        ports:
          - containerPort: 8080
        #imagePullPolicy: Always
        command: [ "/opt/openidm/startup.sh", "-p", "custom/stack-config/openidm"]
        # Note: Docker does not allow mounting on /
        volumeMounts:
          - name: idmconf
            mountPath: /opt/openidm/custom
      volumes:
        - name: idmconf
          gitRepo:
            repository: https://github.com/ForgeRock/stack-config.git
            revision: master
