# Postgres DB for OpenIDM
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    name: idmrepo
spec:
  containers:
  - name: postgres
    image: forgerock/openidm-postgres
    ports:
    - containerPort: 5432
    env:
      - name: PGDATA
        value: /var/lib/postgresql/data/pgdata
      - name: POSTGRES_PASSWORD
        value: openidm
      - name: POSTGRES_USER
        value: openidm
---
# Service definition
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    name: idmrepo
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
