# Postgres DB for OpenIDM
apiVersion: v1
kind: Pod
metadata:
  name: postgres-openidm
  labels:
    name: postgres
spec:
  containers:
  - name: postgres
    image: wstrange/postgres-openidm
    ports:
    - containerPort: 5432

---
# Service definition
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  labels:
    name: db
spec:
  selector:
    name: postgres-openidm
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
