apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openam
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openam
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      #terminationGracePeriodSeconds: 0
      containers:
      - name: openam
        image: forgerock/openam-custom:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: /usr/local/tomcat/webapps/openam
          name: openam
      volumes:
      - name: openam
        hostPath:
          path: /Users/ken.stubbings/dev/tmp/kubedeploy/
#          path: /Users/ken.stubbings/dev/rep/git/newton/openam-newton/openam-server/target/OpenAM-14.0.0-SNAPSHOT/
