# Experimental use of ConfigMap
# Concept: Dynamically configure AM based on configuration template
# The values here get substitued into the AM template that ssoconfig uses
kind: ConfigMap
apiVersion: v1
metadata:
  name: am-config
  namespace: default
data:
  openam.fqdn:  http://openam.example.com:80/openam
  openam.cookiedomain: .example.com
  openam.configurl: https://stash.forgerock.org/projects/DOCKER/repos/fretes/browse/config/openam/01_config.properties?at=master&raw
