# Default values for opendj.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value




dirManagerPassword: password

djInstance: opendj-configstore

persistentVolumes: true

replicaCount: 1

